# Generated by Django 3.2.16 on 2023-01-05 17:16

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', froala_editor.fields.FroalaField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('slug', models.SlugField(editable=False, max_length=500, unique=True)),
                ('category', models.CharField(choices=[('1', 'Programming/Technology'), ('2', 'Health/Fitness'), ('3', 'Personal'), ('4', 'Fashion'), ('5', 'Food'), ('6', 'Travel'), ('7', 'Business'), ('8', 'Art'), ('9', 'Other')], default='1', max_length=20)),
            ],
        ),
    ]
