# Generated by Django 3.2.16 on 2023-01-06 13:38

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Programming/Technology'), ('2', 'Health/Fitness'), ('3', 'Entertainment'), ('4', 'Fashion'), ('5', 'Food'), ('7', 'Business'), ('6', 'Sports'), ('8', 'Health'), ('9', 'Education'), ('10', 'Others')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
